version: '2'
services:
  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-seed:
    container_name: nifi-cluster-seed
    image: thuongdinh/nifi-cluster:latest
    ports:
      - "8080-8082:8080-8082"
    depends_on:
      - zoo1

  nifi-nodes:
    image: thuongdinh/nifi-cluster:latest
    depends_on:
      - nifi-seed
